// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: agent.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
)

const createAgent = `-- name: CreateAgent :one
INSERT INTO agents (id, workspace_id, name, template, description, created_by, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, now(), now())
RETURNING id, workspace_id, name, template, description, created_by, created_at, updated_at
`

type CreateAgentParams struct {
	ID          uuid.UUID
	WorkspaceID string
	Name        string
	Template    string
	Description string
	CreatedBy   string
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, createAgent,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Template,
		arg.Description,
		arg.CreatedBy,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Template,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAgentVersion = `-- name: CreateAgentVersion :one
INSERT INTO agent_versions (id, agent_id, version, snapshot_json, created_by, created_at)
VALUES ($1, $2, $3, $4, $5, now())
RETURNING id, agent_id, version, snapshot_json, created_by, created_at
`

type CreateAgentVersionParams struct {
	ID           uuid.UUID
	AgentID      uuid.UUID
	Version      int32
	SnapshotJson string
	CreatedBy    string
}

func (q *Queries) CreateAgentVersion(ctx context.Context, arg CreateAgentVersionParams) (AgentVersion, error) {
	row := q.db.QueryRow(ctx, createAgentVersion,
		arg.ID,
		arg.AgentID,
		arg.Version,
		arg.SnapshotJson,
		arg.CreatedBy,
	)
	var i AgentVersion
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Version,
		&i.SnapshotJson,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createAgentVersionAndBindDev = `-- name: CreateAgentVersionAndBindDev :exec
WITH inserted_version AS (
  INSERT INTO agent_versions (id, agent_id, version, snapshot_json, created_by, created_at)
  VALUES ($1, $2, $3, $4, $5, now())
  RETURNING id, agent_id
)
INSERT INTO agent_envs (agent_id, env, version_id, updated_at)
SELECT agent_id, 'dev', id, now() FROM inserted_version
ON CONFLICT (agent_id, env) DO UPDATE SET version_id=EXCLUDED.version_id,updated_at=now()
`

type CreateAgentVersionAndBindDevParams struct {
	VersionID    uuid.UUID
	AgentID      uuid.UUID
	Version      int32
	SnapshotJson string
	CreatedBy    string
}

func (q *Queries) CreateAgentVersionAndBindDev(ctx context.Context, arg CreateAgentVersionAndBindDevParams) error {
	_, err := q.db.Exec(ctx, createAgentVersionAndBindDev,
		arg.VersionID,
		arg.AgentID,
		arg.Version,
		arg.SnapshotJson,
		arg.CreatedBy,
	)
	return err
}

const createAgentWithVersion = `-- name: CreateAgentWithVersion :exec
WITH inserted_agent AS (
  INSERT INTO agents (id, workspace_id, name, template, description, created_by, created_at, updated_at)
  VALUES ($1, $2, $3, $4,
          $5, $6, now(), now())
  RETURNING id
), inserted_version AS (
  INSERT INTO agent_versions (id, agent_id, version, snapshot_json, created_by, created_at)
  SELECT $7, id, 1, $8, $9, now()
  FROM inserted_agent
  RETURNING id, agent_id
)
INSERT INTO agent_envs (agent_id, env, version_id, updated_at)
SELECT agent_id, 'dev', id, now() FROM inserted_version
`

type CreateAgentWithVersionParams struct {
	AgentID          uuid.UUID
	WorkspaceID      string
	Name             string
	Template         string
	Description      string
	AgentCreatedBy   string
	VersionID        uuid.UUID
	SnapshotJson     string
	VersionCreatedBy string
}

func (q *Queries) CreateAgentWithVersion(ctx context.Context, arg CreateAgentWithVersionParams) error {
	_, err := q.db.Exec(ctx, createAgentWithVersion,
		arg.AgentID,
		arg.WorkspaceID,
		arg.Name,
		arg.Template,
		arg.Description,
		arg.AgentCreatedBy,
		arg.VersionID,
		arg.SnapshotJson,
		arg.VersionCreatedBy,
	)
	return err
}

const getAgent = `-- name: GetAgent :one

SELECT id, workspace_id, name, template, description, created_by, created_at, updated_at FROM agents WHERE id = $1 LIMIT 1
`

// Agent:agents / agent_versions / agent_envs
// 「当前版本」走 env 指针(agent_envs);CreateAgentVersion 由 store 自动把新版本绑到 dev(对齐 memory 语义)。
func (q *Queries) GetAgent(ctx context.Context, id uuid.UUID) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgent, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Template,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentCurrentVersion = `-- name: GetAgentCurrentVersion :one
SELECT av.id, av.agent_id, av.version, av.snapshot_json, av.created_by, av.created_at FROM agent_versions av
JOIN agent_envs ae ON ae.version_id = av.id
WHERE ae.agent_id = $1 AND ae.env = $2
LIMIT 1
`

type GetAgentCurrentVersionParams struct {
	AgentID uuid.UUID
	Env     string
}

func (q *Queries) GetAgentCurrentVersion(ctx context.Context, arg GetAgentCurrentVersionParams) (AgentVersion, error) {
	row := q.db.QueryRow(ctx, getAgentCurrentVersion, arg.AgentID, arg.Env)
	var i AgentVersion
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Version,
		&i.SnapshotJson,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getAgentVersion = `-- name: GetAgentVersion :one
SELECT id, agent_id, version, snapshot_json, created_by, created_at FROM agent_versions WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAgentVersion(ctx context.Context, id uuid.UUID) (AgentVersion, error) {
	row := q.db.QueryRow(ctx, getAgentVersion, id)
	var i AgentVersion
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Version,
		&i.SnapshotJson,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listAgentVersions = `-- name: ListAgentVersions :many
SELECT id, agent_id, version, snapshot_json, created_by, created_at FROM agent_versions WHERE agent_id = $1 ORDER BY version DESC
`

func (q *Queries) ListAgentVersions(ctx context.Context, agentID uuid.UUID) ([]AgentVersion, error) {
	rows, err := q.db.Query(ctx, listAgentVersions, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentVersion{}
	for rows.Next() {
		var i AgentVersion
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Version,
			&i.SnapshotJson,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgents = `-- name: ListAgents :many
SELECT id, workspace_id, name, template, description, created_by, created_at, updated_at FROM agents WHERE workspace_id = $1 ORDER BY created_at
`

func (q *Queries) ListAgents(ctx context.Context, workspaceID string) ([]Agent, error) {
	rows, err := q.db.Query(ctx, listAgents, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Template,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAgentEnv = `-- name: UpsertAgentEnv :exec
INSERT INTO agent_envs (agent_id, env, version_id, updated_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (agent_id, env) DO UPDATE
SET version_id = EXCLUDED.version_id, updated_at = now()
`

type UpsertAgentEnvParams struct {
	AgentID   uuid.UUID
	Env       string
	VersionID uuid.UUID
}

func (q *Queries) UpsertAgentEnv(ctx context.Context, arg UpsertAgentEnvParams) error {
	_, err := q.db.Exec(ctx, upsertAgentEnv, arg.AgentID, arg.Env, arg.VersionID)
	return err
}
