// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: audit.sql

package pgstore

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditLog = `-- name: InsertAuditLog :exec

INSERT INTO audit_logs (workspace_id, actor, action, resource_type, resource_id, before_json, after_json, ip, ua, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertAuditLogParams struct {
	WorkspaceID  string
	Actor        string
	Action       string
	ResourceType string
	ResourceID   string
	BeforeJson   pgtype.Text
	AfterJson    pgtype.Text
	Ip           pgtype.Text
	Ua           pgtype.Text
	CreatedAt    time.Time
}

// Audit:audit_logs(分区父表,查询透明走分区)
func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.WorkspaceID,
		arg.Actor,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.BeforeJson,
		arg.AfterJson,
		arg.Ip,
		arg.Ua,
		arg.CreatedAt,
	)
	return err
}

const insertSkillTrigger = `-- name: InsertSkillTrigger :exec
INSERT INTO skill_triggers (
    id, workspace_id, conversation_id, skill_version_id, skill_name, source, success, triggered_at
)
VALUES ($1, $2, $3, $4, $5, $6, true, now())
`

type InsertSkillTriggerParams struct {
	ID             uuid.UUID
	WorkspaceID    string
	ConversationID uuid.UUID
	SkillVersionID pgtype.UUID
	SkillName      string
	Source         string
}

func (q *Queries) InsertSkillTrigger(ctx context.Context, arg InsertSkillTriggerParams) error {
	_, err := q.db.Exec(ctx, insertSkillTrigger,
		arg.ID,
		arg.WorkspaceID,
		arg.ConversationID,
		arg.SkillVersionID,
		arg.SkillName,
		arg.Source,
	)
	return err
}

const queryAuditLogs = `-- name: QueryAuditLogs :many
SELECT id, actor, action, resource_type, resource_id, before_json, after_json, ip, ua, created_at, workspace_id FROM audit_logs
WHERE workspace_id = $1::text
  AND ($2::text = '' OR actor = $2::text)
  AND ($3::text = '' OR resource_type = $3::text)
  AND ($4::text = '' OR (resource_type = 'conversation' AND resource_id = $4::text))
ORDER BY created_at DESC
LIMIT NULLIF($5::int, 0)
`

type QueryAuditLogsParams struct {
	WorkspaceID    string
	Actor          string
	ResourceType   string
	ConversationID string
	Lim            int32
}

// QueryAuditLogs:可选过滤(actor / resource_type / conversation),倒序最新优先。
// limit 为 0 时 NULLIF→NULL,即不限制(对齐 memory 版 Limit<=0 返回全部)。
func (q *Queries) QueryAuditLogs(ctx context.Context, arg QueryAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, queryAuditLogs,
		arg.WorkspaceID,
		arg.Actor,
		arg.ResourceType,
		arg.ConversationID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.Actor,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.BeforeJson,
			&i.AfterJson,
			&i.Ip,
			&i.Ua,
			&i.CreatedAt,
			&i.WorkspaceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
