// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: conversation.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCheckpoint = `-- name: CreateCheckpoint :exec
INSERT INTO checkpoints (id, conversation_id, approval_id, state_snapshot, created_at)
VALUES ($1, $2, $3, $4, now())
`

type CreateCheckpointParams struct {
	ID             uuid.UUID
	ConversationID uuid.UUID
	ApprovalID     pgtype.UUID
	StateSnapshot  []byte
}

func (q *Queries) CreateCheckpoint(ctx context.Context, arg CreateCheckpointParams) error {
	_, err := q.db.Exec(ctx, createCheckpoint,
		arg.ID,
		arg.ConversationID,
		arg.ApprovalID,
		arg.StateSnapshot,
	)
	return err
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (id, agent_id, agent_version_id, user_id, workspace_id, classification, status, started_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, now(), now())
RETURNING id, agent_id, agent_version_id, user_id, workspace_id, classification, status, started_at, updated_at, turn_token, turn_lease_until, turn_revision
`

type CreateConversationParams struct {
	ID             uuid.UUID
	AgentID        string
	AgentVersionID string
	UserID         string
	WorkspaceID    string
	Classification string
	Status         string
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation,
		arg.ID,
		arg.AgentID,
		arg.AgentVersionID,
		arg.UserID,
		arg.WorkspaceID,
		arg.Classification,
		arg.Status,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.AgentVersionID,
		&i.UserID,
		&i.WorkspaceID,
		&i.Classification,
		&i.Status,
		&i.StartedAt,
		&i.UpdatedAt,
		&i.TurnToken,
		&i.TurnLeaseUntil,
		&i.TurnRevision,
	)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (id, conversation_id, role, content, tool_calls, tool_call_id, created_at)
VALUES ($1, $2, $3, $4, $5, $6, now())
RETURNING id, conversation_id, role, content, tool_calls, tool_call_id, created_at
`

type CreateMessageParams struct {
	ID             uuid.UUID
	ConversationID uuid.UUID
	Role           string
	Content        string
	ToolCalls      []byte
	ToolCallID     pgtype.Text
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ID,
		arg.ConversationID,
		arg.Role,
		arg.Content,
		arg.ToolCalls,
		arg.ToolCallID,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Role,
		&i.Content,
		&i.ToolCalls,
		&i.ToolCallID,
		&i.CreatedAt,
	)
	return i, err
}

const getCheckpointForApproval = `-- name: GetCheckpointForApproval :one
SELECT id, conversation_id, state_snapshot, created_at, approval_id FROM checkpoints WHERE approval_id = $1 AND conversation_id = $2 LIMIT 1
`

type GetCheckpointForApprovalParams struct {
	ApprovalID     pgtype.UUID
	ConversationID uuid.UUID
}

func (q *Queries) GetCheckpointForApproval(ctx context.Context, arg GetCheckpointForApprovalParams) (Checkpoint, error) {
	row := q.db.QueryRow(ctx, getCheckpointForApproval, arg.ApprovalID, arg.ConversationID)
	var i Checkpoint
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.StateSnapshot,
		&i.CreatedAt,
		&i.ApprovalID,
	)
	return i, err
}

const getConversation = `-- name: GetConversation :one

SELECT id, agent_id, agent_version_id, user_id, workspace_id, classification, status, started_at, updated_at, turn_token, turn_lease_until, turn_revision FROM conversations WHERE id = $1 LIMIT 1
`

// Conversation:conversations / messages(agent.Store 的会话部分)
func (q *Queries) GetConversation(ctx context.Context, id uuid.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversation, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.AgentVersionID,
		&i.UserID,
		&i.WorkspaceID,
		&i.Classification,
		&i.Status,
		&i.StartedAt,
		&i.UpdatedAt,
		&i.TurnToken,
		&i.TurnLeaseUntil,
		&i.TurnRevision,
	)
	return i, err
}

const listConversations = `-- name: ListConversations :many
SELECT id, agent_id, agent_version_id, user_id, workspace_id, classification, status, started_at, updated_at, turn_token, turn_lease_until, turn_revision FROM conversations
WHERE workspace_id = $1
  AND user_id = $2
  AND ($3::text = '' OR agent_id = $3)
ORDER BY updated_at DESC, started_at DESC
LIMIT $5::int OFFSET $4::int
`

type ListConversationsParams struct {
	WorkspaceID string
	UserID      string
	AgentID     string
	PageOffset  int32
	PageLimit   int32
}

func (q *Queries) ListConversations(ctx context.Context, arg ListConversationsParams) ([]Conversation, error) {
	rows, err := q.db.Query(ctx, listConversations,
		arg.WorkspaceID,
		arg.UserID,
		arg.AgentID,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Conversation{}
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.AgentVersionID,
			&i.UserID,
			&i.WorkspaceID,
			&i.Classification,
			&i.Status,
			&i.StartedAt,
			&i.UpdatedAt,
			&i.TurnToken,
			&i.TurnLeaseUntil,
			&i.TurnRevision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT id, conversation_id, role, content, tool_calls, tool_call_id, created_at FROM messages WHERE conversation_id = $1 ORDER BY created_at
`

func (q *Queries) ListMessages(ctx context.Context, conversationID uuid.UUID) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessages, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Role,
			&i.Content,
			&i.ToolCalls,
			&i.ToolCallID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
