// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: guard.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const beginApprovalExecution = `-- name: BeginApprovalExecution :one
UPDATE approvals
SET execution_status = 'executing', execution_started_at = now(), execution_completed_at = NULL,
    execution_error = '', execution_lease_until = now() + interval '2 minutes',
    execution_attempts = execution_attempts + 1, execution_token = $1
WHERE id = $2
  AND conversation_id = $3
  AND status = 'approved'
  AND execution_attempts < 5
  AND (
      execution_status = 'not_started'
      OR execution_status = 'failed'
      OR (execution_status = 'executing' AND execution_lease_until < now())
  )
RETURNING id, conversation_id, action, payload, status, approver_id, created_at, resolved_at, workspace_id, execution_status, execution_started_at, execution_completed_at, execution_error, execution_lease_until, execution_attempts, execution_token
`

type BeginApprovalExecutionParams struct {
	ExecutionToken pgtype.UUID
	ID             uuid.UUID
	ConversationID pgtype.UUID
}

func (q *Queries) BeginApprovalExecution(ctx context.Context, arg BeginApprovalExecutionParams) (Approval, error) {
	row := q.db.QueryRow(ctx, beginApprovalExecution, arg.ExecutionToken, arg.ID, arg.ConversationID)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Action,
		&i.Payload,
		&i.Status,
		&i.ApproverID,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.WorkspaceID,
		&i.ExecutionStatus,
		&i.ExecutionStartedAt,
		&i.ExecutionCompletedAt,
		&i.ExecutionError,
		&i.ExecutionLeaseUntil,
		&i.ExecutionAttempts,
		&i.ExecutionToken,
	)
	return i, err
}

const completeApprovalExecution = `-- name: CompleteApprovalExecution :execrows
UPDATE approvals
SET execution_status = 'completed', execution_completed_at = now(), execution_error = '',
    execution_lease_until = NULL, execution_token = NULL
WHERE id = $1 AND execution_status = 'executing'
  AND execution_token = $2
`

type CompleteApprovalExecutionParams struct {
	ID             uuid.UUID
	ExecutionToken pgtype.UUID
}

func (q *Queries) CompleteApprovalExecution(ctx context.Context, arg CompleteApprovalExecutionParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeApprovalExecution, arg.ID, arg.ExecutionToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const consumeQuota = `-- name: ConsumeQuota :one
UPDATE quota_ledger
SET used = used + $1::bigint
WHERE dimension = $2 AND period = $3
  AND (lim = 0 OR used + $1::bigint <= lim)
RETURNING dimension, period, used, lim
`

type ConsumeQuotaParams struct {
	Amount    int64
	Dimension string
	Period    string
}

func (q *Queries) ConsumeQuota(ctx context.Context, arg ConsumeQuotaParams) (QuotaLedger, error) {
	row := q.db.QueryRow(ctx, consumeQuota, arg.Amount, arg.Dimension, arg.Period)
	var i QuotaLedger
	err := row.Scan(
		&i.Dimension,
		&i.Period,
		&i.Used,
		&i.Lim,
	)
	return i, err
}

const createApproval = `-- name: CreateApproval :one
INSERT INTO approvals (id, workspace_id, conversation_id, action, payload, status, created_at)
VALUES ($1, $2, $3, $4, $5, 'pending', now())
RETURNING id, conversation_id, action, payload, status, approver_id, created_at, resolved_at, workspace_id, execution_status, execution_started_at, execution_completed_at, execution_error, execution_lease_until, execution_attempts, execution_token
`

type CreateApprovalParams struct {
	ID             uuid.UUID
	WorkspaceID    string
	ConversationID pgtype.UUID
	Action         string
	Payload        []byte
}

func (q *Queries) CreateApproval(ctx context.Context, arg CreateApprovalParams) (Approval, error) {
	row := q.db.QueryRow(ctx, createApproval,
		arg.ID,
		arg.WorkspaceID,
		arg.ConversationID,
		arg.Action,
		arg.Payload,
	)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Action,
		&i.Payload,
		&i.Status,
		&i.ApproverID,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.WorkspaceID,
		&i.ExecutionStatus,
		&i.ExecutionStartedAt,
		&i.ExecutionCompletedAt,
		&i.ExecutionError,
		&i.ExecutionLeaseUntil,
		&i.ExecutionAttempts,
		&i.ExecutionToken,
	)
	return i, err
}

const createGuardRule = `-- name: CreateGuardRule :one
INSERT INTO guard_rules (id, kind, hook, pattern_or_model, action, enabled, workspace_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, kind, hook, pattern_or_model, action, enabled, workspace_id
`

type CreateGuardRuleParams struct {
	ID             uuid.UUID
	Kind           string
	Hook           string
	PatternOrModel string
	Action         string
	Enabled        bool
	WorkspaceID    string
}

func (q *Queries) CreateGuardRule(ctx context.Context, arg CreateGuardRuleParams) (GuardRule, error) {
	row := q.db.QueryRow(ctx, createGuardRule,
		arg.ID,
		arg.Kind,
		arg.Hook,
		arg.PatternOrModel,
		arg.Action,
		arg.Enabled,
		arg.WorkspaceID,
	)
	var i GuardRule
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Hook,
		&i.PatternOrModel,
		&i.Action,
		&i.Enabled,
		&i.WorkspaceID,
	)
	return i, err
}

const failApprovalExecution = `-- name: FailApprovalExecution :execrows
UPDATE approvals
SET execution_status = 'failed', execution_completed_at = now(), execution_error = $1,
    execution_lease_until = NULL, execution_token = NULL
WHERE id = $2 AND execution_status = 'executing'
  AND execution_token = $3
`

type FailApprovalExecutionParams struct {
	ExecutionError string
	ID             uuid.UUID
	ExecutionToken pgtype.UUID
}

func (q *Queries) FailApprovalExecution(ctx context.Context, arg FailApprovalExecutionParams) (int64, error) {
	result, err := q.db.Exec(ctx, failApprovalExecution, arg.ExecutionError, arg.ID, arg.ExecutionToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getApproval = `-- name: GetApproval :one
SELECT id, conversation_id, action, payload, status, approver_id, created_at, resolved_at, workspace_id, execution_status, execution_started_at, execution_completed_at, execution_error, execution_lease_until, execution_attempts, execution_token FROM approvals WHERE id = $1 LIMIT 1
`

func (q *Queries) GetApproval(ctx context.Context, id uuid.UUID) (Approval, error) {
	row := q.db.QueryRow(ctx, getApproval, id)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Action,
		&i.Payload,
		&i.Status,
		&i.ApproverID,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.WorkspaceID,
		&i.ExecutionStatus,
		&i.ExecutionStartedAt,
		&i.ExecutionCompletedAt,
		&i.ExecutionError,
		&i.ExecutionLeaseUntil,
		&i.ExecutionAttempts,
		&i.ExecutionToken,
	)
	return i, err
}

const getGuardRule = `-- name: GetGuardRule :one
SELECT id, kind, hook, pattern_or_model, action, enabled, workspace_id FROM guard_rules WHERE id = $1 LIMIT 1
`

func (q *Queries) GetGuardRule(ctx context.Context, id uuid.UUID) (GuardRule, error) {
	row := q.db.QueryRow(ctx, getGuardRule, id)
	var i GuardRule
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Hook,
		&i.PatternOrModel,
		&i.Action,
		&i.Enabled,
		&i.WorkspaceID,
	)
	return i, err
}

const getQuota = `-- name: GetQuota :one
SELECT dimension, period, used, lim FROM quota_ledger WHERE dimension = $1 AND period = $2 LIMIT 1
`

type GetQuotaParams struct {
	Dimension string
	Period    string
}

func (q *Queries) GetQuota(ctx context.Context, arg GetQuotaParams) (QuotaLedger, error) {
	row := q.db.QueryRow(ctx, getQuota, arg.Dimension, arg.Period)
	var i QuotaLedger
	err := row.Scan(
		&i.Dimension,
		&i.Period,
		&i.Used,
		&i.Lim,
	)
	return i, err
}

const insertInjectionLog = `-- name: InsertInjectionLog :one
INSERT INTO injection_logs (id, conversation_id, sample, rule_id, severity, created_at)
VALUES ($1, $2, $3, $4, $5, now())
RETURNING id, conversation_id, sample, rule_id, severity, created_at
`

type InsertInjectionLogParams struct {
	ID             uuid.UUID
	ConversationID pgtype.UUID
	Sample         string
	RuleID         pgtype.UUID
	Severity       string
}

func (q *Queries) InsertInjectionLog(ctx context.Context, arg InsertInjectionLogParams) (InjectionLog, error) {
	row := q.db.QueryRow(ctx, insertInjectionLog,
		arg.ID,
		arg.ConversationID,
		arg.Sample,
		arg.RuleID,
		arg.Severity,
	)
	var i InjectionLog
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Sample,
		&i.RuleID,
		&i.Severity,
		&i.CreatedAt,
	)
	return i, err
}

const listApprovalsByConversation = `-- name: ListApprovalsByConversation :many
SELECT id, conversation_id, action, payload, status, approver_id, created_at, resolved_at, workspace_id, execution_status, execution_started_at, execution_completed_at, execution_error, execution_lease_until, execution_attempts, execution_token FROM approvals WHERE conversation_id = $1 ORDER BY created_at
`

func (q *Queries) ListApprovalsByConversation(ctx context.Context, conversationID pgtype.UUID) ([]Approval, error) {
	rows, err := q.db.Query(ctx, listApprovalsByConversation, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Approval{}
	for rows.Next() {
		var i Approval
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Action,
			&i.Payload,
			&i.Status,
			&i.ApproverID,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.WorkspaceID,
			&i.ExecutionStatus,
			&i.ExecutionStartedAt,
			&i.ExecutionCompletedAt,
			&i.ExecutionError,
			&i.ExecutionLeaseUntil,
			&i.ExecutionAttempts,
			&i.ExecutionToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGuardRules = `-- name: ListGuardRules :many

SELECT id, kind, hook, pattern_or_model, action, enabled, workspace_id FROM guard_rules WHERE workspace_id = $1 ORDER BY kind, hook, id
`

// Guard:guard_rules / injection_logs / quota_ledger / approvals
func (q *Queries) ListGuardRules(ctx context.Context, workspaceID string) ([]GuardRule, error) {
	rows, err := q.db.Query(ctx, listGuardRules, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GuardRule{}
	for rows.Next() {
		var i GuardRule
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Hook,
			&i.PatternOrModel,
			&i.Action,
			&i.Enabled,
			&i.WorkspaceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInjectionLogs = `-- name: ListInjectionLogs :many
SELECT id, conversation_id, sample, rule_id, severity, created_at FROM injection_logs WHERE conversation_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListInjectionLogs(ctx context.Context, conversationID pgtype.UUID) ([]InjectionLog, error) {
	rows, err := q.db.Query(ctx, listInjectionLogs, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InjectionLog{}
	for rows.Next() {
		var i InjectionLog
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Sample,
			&i.RuleID,
			&i.Severity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingApprovals = `-- name: ListPendingApprovals :many
SELECT id, conversation_id, action, payload, status, approver_id, created_at, resolved_at, workspace_id, execution_status, execution_started_at, execution_completed_at, execution_error, execution_lease_until, execution_attempts, execution_token FROM approvals
WHERE workspace_id = $1 AND status = 'pending'
ORDER BY created_at DESC
`

func (q *Queries) ListPendingApprovals(ctx context.Context, workspaceID string) ([]Approval, error) {
	rows, err := q.db.Query(ctx, listPendingApprovals, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Approval{}
	for rows.Next() {
		var i Approval
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Action,
			&i.Payload,
			&i.Status,
			&i.ApproverID,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.WorkspaceID,
			&i.ExecutionStatus,
			&i.ExecutionStartedAt,
			&i.ExecutionCompletedAt,
			&i.ExecutionError,
			&i.ExecutionLeaseUntil,
			&i.ExecutionAttempts,
			&i.ExecutionToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadyApprovalResumes = `-- name: ListReadyApprovalResumes :many
SELECT id, conversation_id, action, payload, status, approver_id, created_at, resolved_at, workspace_id, execution_status, execution_started_at, execution_completed_at, execution_error, execution_lease_until, execution_attempts, execution_token FROM approvals
WHERE status = 'approved'
  AND execution_attempts < 5
  AND (
      execution_status = 'not_started'
      OR execution_status = 'failed'
      OR (execution_status = 'executing' AND execution_lease_until < now())
  )
ORDER BY resolved_at ASC
LIMIT $1
`

func (q *Queries) ListReadyApprovalResumes(ctx context.Context, limit int32) ([]Approval, error) {
	rows, err := q.db.Query(ctx, listReadyApprovalResumes, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Approval{}
	for rows.Next() {
		var i Approval
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Action,
			&i.Payload,
			&i.Status,
			&i.ApproverID,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.WorkspaceID,
			&i.ExecutionStatus,
			&i.ExecutionStartedAt,
			&i.ExecutionCompletedAt,
			&i.ExecutionError,
			&i.ExecutionLeaseUntil,
			&i.ExecutionAttempts,
			&i.ExecutionToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceQuotas = `-- name: ListWorkspaceQuotas :many
SELECT dimension, period, used, lim FROM quota_ledger
WHERE dimension LIKE 'workspace:' || $1::text || ':%'
  AND period = $2
ORDER BY dimension
`

type ListWorkspaceQuotasParams struct {
	WorkspaceID string
	Period      string
}

func (q *Queries) ListWorkspaceQuotas(ctx context.Context, arg ListWorkspaceQuotasParams) ([]QuotaLedger, error) {
	rows, err := q.db.Query(ctx, listWorkspaceQuotas, arg.WorkspaceID, arg.Period)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QuotaLedger{}
	for rows.Next() {
		var i QuotaLedger
		if err := rows.Scan(
			&i.Dimension,
			&i.Period,
			&i.Used,
			&i.Lim,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renewApprovalExecution = `-- name: RenewApprovalExecution :execrows
UPDATE approvals
SET execution_lease_until = now() + interval '2 minutes'
WHERE id = $1
  AND execution_status = 'executing'
  AND execution_token = $2
`

type RenewApprovalExecutionParams struct {
	ID             uuid.UUID
	ExecutionToken pgtype.UUID
}

func (q *Queries) RenewApprovalExecution(ctx context.Context, arg RenewApprovalExecutionParams) (int64, error) {
	result, err := q.db.Exec(ctx, renewApprovalExecution, arg.ID, arg.ExecutionToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resolvePendingApproval = `-- name: ResolvePendingApproval :one
UPDATE approvals
SET status = $1, approver_id = $2, resolved_at = now()
WHERE id = $3
  AND workspace_id = $4
  AND status = 'pending'
RETURNING id, conversation_id, action, payload, status, approver_id, created_at, resolved_at, workspace_id, execution_status, execution_started_at, execution_completed_at, execution_error, execution_lease_until, execution_attempts, execution_token
`

type ResolvePendingApprovalParams struct {
	Status      string
	ApproverID  pgtype.UUID
	ID          uuid.UUID
	WorkspaceID string
}

func (q *Queries) ResolvePendingApproval(ctx context.Context, arg ResolvePendingApprovalParams) (Approval, error) {
	row := q.db.QueryRow(ctx, resolvePendingApproval,
		arg.Status,
		arg.ApproverID,
		arg.ID,
		arg.WorkspaceID,
	)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Action,
		&i.Payload,
		&i.Status,
		&i.ApproverID,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.WorkspaceID,
		&i.ExecutionStatus,
		&i.ExecutionStartedAt,
		&i.ExecutionCompletedAt,
		&i.ExecutionError,
		&i.ExecutionLeaseUntil,
		&i.ExecutionAttempts,
		&i.ExecutionToken,
	)
	return i, err
}

const setQuotaLimit = `-- name: SetQuotaLimit :one
INSERT INTO quota_ledger (dimension, period, used, lim)
VALUES ($1, $2, 0, $3)
ON CONFLICT (dimension, period) DO UPDATE SET lim = EXCLUDED.lim
RETURNING dimension, period, used, lim
`

type SetQuotaLimitParams struct {
	Dimension string
	Period    string
	Lim       int64
}

func (q *Queries) SetQuotaLimit(ctx context.Context, arg SetQuotaLimitParams) (QuotaLedger, error) {
	row := q.db.QueryRow(ctx, setQuotaLimit, arg.Dimension, arg.Period, arg.Lim)
	var i QuotaLedger
	err := row.Scan(
		&i.Dimension,
		&i.Period,
		&i.Used,
		&i.Lim,
	)
	return i, err
}

const updateGuardRule = `-- name: UpdateGuardRule :one
UPDATE guard_rules
SET kind = $2, hook = $3, pattern_or_model = $4, action = $5, enabled = $6
WHERE id = $1
RETURNING id, kind, hook, pattern_or_model, action, enabled, workspace_id
`

type UpdateGuardRuleParams struct {
	ID             uuid.UUID
	Kind           string
	Hook           string
	PatternOrModel string
	Action         string
	Enabled        bool
}

func (q *Queries) UpdateGuardRule(ctx context.Context, arg UpdateGuardRuleParams) (GuardRule, error) {
	row := q.db.QueryRow(ctx, updateGuardRule,
		arg.ID,
		arg.Kind,
		arg.Hook,
		arg.PatternOrModel,
		arg.Action,
		arg.Enabled,
	)
	var i GuardRule
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Hook,
		&i.PatternOrModel,
		&i.Action,
		&i.Enabled,
		&i.WorkspaceID,
	)
	return i, err
}
