// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: jobs.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDeadLetter = `-- name: CreateDeadLetter :one
INSERT INTO dead_letters (id, job_id, payload, error, dlq_at)
VALUES ($1, $2, $3, $4, now())
RETURNING id, job_id, payload, error, dlq_at
`

type CreateDeadLetterParams struct {
	ID      uuid.UUID
	JobID   pgtype.UUID
	Payload []byte
	Error   string
}

func (q *Queries) CreateDeadLetter(ctx context.Context, arg CreateDeadLetterParams) (DeadLetter, error) {
	row := q.db.QueryRow(ctx, createDeadLetter,
		arg.ID,
		arg.JobID,
		arg.Payload,
		arg.Error,
	)
	var i DeadLetter
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Payload,
		&i.Error,
		&i.DlqAt,
	)
	return i, err
}

const createJob = `-- name: CreateJob :one

INSERT INTO jobs (id, workspace_id, type, payload, status, scheduled_at, idempotency_key)
VALUES ($1, $2, $3, $4, 'pending', $5, $6)
RETURNING id, workspace_id, type, payload, status, attempts, scheduled_at, started_at, finished_at, error, idempotency_key
`

type CreateJobParams struct {
	ID             uuid.UUID
	WorkspaceID    string
	Type           string
	Payload        []byte
	ScheduledAt    pgtype.Timestamptz
	IdempotencyKey pgtype.Text
}

// Jobs:jobs / job_schedules / dead_letters
func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.ID,
		arg.WorkspaceID,
		arg.Type,
		arg.Payload,
		arg.ScheduledAt,
		arg.IdempotencyKey,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Type,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Error,
		&i.IdempotencyKey,
	)
	return i, err
}

const createJobSchedule = `-- name: CreateJobSchedule :one
INSERT INTO job_schedules (id, type, payload, cron, next_run_at, enabled)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, type, payload, cron, next_run_at, enabled
`

type CreateJobScheduleParams struct {
	ID        uuid.UUID
	Type      string
	Payload   []byte
	Cron      string
	NextRunAt pgtype.Timestamptz
	Enabled   bool
}

func (q *Queries) CreateJobSchedule(ctx context.Context, arg CreateJobScheduleParams) (JobSchedule, error) {
	row := q.db.QueryRow(ctx, createJobSchedule,
		arg.ID,
		arg.Type,
		arg.Payload,
		arg.Cron,
		arg.NextRunAt,
		arg.Enabled,
	)
	var i JobSchedule
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Payload,
		&i.Cron,
		&i.NextRunAt,
		&i.Enabled,
	)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT id, workspace_id, type, payload, status, attempts, scheduled_at, started_at, finished_at, error, idempotency_key FROM jobs WHERE id = $1 LIMIT 1
`

func (q *Queries) GetJob(ctx context.Context, id uuid.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Type,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Error,
		&i.IdempotencyKey,
	)
	return i, err
}

const listEnabledSchedules = `-- name: ListEnabledSchedules :many
SELECT id, type, payload, cron, next_run_at, enabled FROM job_schedules WHERE enabled = true
`

func (q *Queries) ListEnabledSchedules(ctx context.Context) ([]JobSchedule, error) {
	rows, err := q.db.Query(ctx, listEnabledSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobSchedule{}
	for rows.Next() {
		var i JobSchedule
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Payload,
			&i.Cron,
			&i.NextRunAt,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingJobs = `-- name: ListPendingJobs :many
SELECT id, workspace_id, type, payload, status, attempts, scheduled_at, started_at, finished_at, error, idempotency_key FROM jobs WHERE status = 'pending' ORDER BY scheduled_at NULLS FIRST LIMIT $1
`

func (q *Queries) ListPendingJobs(ctx context.Context, limit int32) ([]Job, error) {
	rows, err := q.db.Query(ctx, listPendingJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Type,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.ScheduledAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Error,
			&i.IdempotencyKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobStatus = `-- name: UpdateJobStatus :exec
UPDATE jobs SET status = $2, attempts = $3, started_at = $4, finished_at = $5, error = $6 WHERE id = $1
`

type UpdateJobStatusParams struct {
	ID         uuid.UUID
	Status     string
	Attempts   int32
	StartedAt  pgtype.Timestamptz
	FinishedAt pgtype.Timestamptz
	Error      string
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) error {
	_, err := q.db.Exec(ctx, updateJobStatus,
		arg.ID,
		arg.Status,
		arg.Attempts,
		arg.StartedAt,
		arg.FinishedAt,
		arg.Error,
	)
	return err
}
