// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: kb.sql

package pgstore

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createIngestJob = `-- name: CreateIngestJob :exec
INSERT INTO kb_ingest_jobs (id, kb_id, doc_id, stage, retries, error, started_at, finished_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateIngestJobParams struct {
	ID         uuid.UUID
	KbID       uuid.UUID
	DocID      uuid.UUID
	Stage      string
	Retries    int32
	Error      pgtype.Text
	StartedAt  time.Time
	FinishedAt pgtype.Timestamptz
}

func (q *Queries) CreateIngestJob(ctx context.Context, arg CreateIngestJobParams) error {
	_, err := q.db.Exec(ctx, createIngestJob,
		arg.ID,
		arg.KbID,
		arg.DocID,
		arg.Stage,
		arg.Retries,
		arg.Error,
		arg.StartedAt,
		arg.FinishedAt,
	)
	return err
}

const createKB = `-- name: CreateKB :one
INSERT INTO kbs (id, workspace_id, name, chunking_config, embedding_model, status, created_by, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, now(), now())
RETURNING id, workspace_id, name, chunking_config, embedding_model, status, created_by, created_at, updated_at
`

type CreateKBParams struct {
	ID             uuid.UUID
	WorkspaceID    string
	Name           string
	ChunkingConfig string
	EmbeddingModel string
	Status         string
	CreatedBy      string
}

func (q *Queries) CreateKB(ctx context.Context, arg CreateKBParams) (Kb, error) {
	row := q.db.QueryRow(ctx, createKB,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.ChunkingConfig,
		arg.EmbeddingModel,
		arg.Status,
		arg.CreatedBy,
	)
	var i Kb
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.ChunkingConfig,
		&i.EmbeddingModel,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDocument = `-- name: GetDocument :one
SELECT id, kb_id, source_type, source_uri, hash, classification, status, ingested_at, created_at FROM kb_documents WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDocument(ctx context.Context, id uuid.UUID) (KbDocument, error) {
	row := q.db.QueryRow(ctx, getDocument, id)
	var i KbDocument
	err := row.Scan(
		&i.ID,
		&i.KbID,
		&i.SourceType,
		&i.SourceUri,
		&i.Hash,
		&i.Classification,
		&i.Status,
		&i.IngestedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getKB = `-- name: GetKB :one

SELECT id, workspace_id, name, chunking_config, embedding_model, status, created_by, created_at, updated_at FROM kbs WHERE id = $1 LIMIT 1
`

// KB:kbs / kb_documents / kb_ingest_jobs / connector_instances
// kb_chunks 的写入与向量/全文检索由 runtime/retriever 的 PostgreSQL 实现负责。
func (q *Queries) GetKB(ctx context.Context, id uuid.UUID) (Kb, error) {
	row := q.db.QueryRow(ctx, getKB, id)
	var i Kb
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.ChunkingConfig,
		&i.EmbeddingModel,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConnectors = `-- name: ListConnectors :many
SELECT id, kb_id, connector_kind, config_json, cursor, last_sync_at, created_at FROM connector_instances WHERE kb_id = $1 ORDER BY created_at
`

func (q *Queries) ListConnectors(ctx context.Context, kbID uuid.UUID) ([]ConnectorInstance, error) {
	rows, err := q.db.Query(ctx, listConnectors, kbID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConnectorInstance{}
	for rows.Next() {
		var i ConnectorInstance
		if err := rows.Scan(
			&i.ID,
			&i.KbID,
			&i.ConnectorKind,
			&i.ConfigJson,
			&i.Cursor,
			&i.LastSyncAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocuments = `-- name: ListDocuments :many
SELECT id, kb_id, source_type, source_uri, hash, classification, status, ingested_at, created_at FROM kb_documents WHERE kb_id = $1 ORDER BY created_at
`

func (q *Queries) ListDocuments(ctx context.Context, kbID uuid.UUID) ([]KbDocument, error) {
	rows, err := q.db.Query(ctx, listDocuments, kbID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KbDocument{}
	for rows.Next() {
		var i KbDocument
		if err := rows.Scan(
			&i.ID,
			&i.KbID,
			&i.SourceType,
			&i.SourceUri,
			&i.Hash,
			&i.Classification,
			&i.Status,
			&i.IngestedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIngestJobs = `-- name: ListIngestJobs :many
SELECT id, kb_id, doc_id, stage, retries, error, started_at, finished_at FROM kb_ingest_jobs WHERE kb_id = $1 ORDER BY started_at
`

func (q *Queries) ListIngestJobs(ctx context.Context, kbID uuid.UUID) ([]KbIngestJob, error) {
	rows, err := q.db.Query(ctx, listIngestJobs, kbID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KbIngestJob{}
	for rows.Next() {
		var i KbIngestJob
		if err := rows.Scan(
			&i.ID,
			&i.KbID,
			&i.DocID,
			&i.Stage,
			&i.Retries,
			&i.Error,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKBs = `-- name: ListKBs :many
SELECT id, workspace_id, name, chunking_config, embedding_model, status, created_by, created_at, updated_at FROM kbs WHERE workspace_id = $1 ORDER BY created_at
`

func (q *Queries) ListKBs(ctx context.Context, workspaceID string) ([]Kb, error) {
	rows, err := q.db.Query(ctx, listKBs, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Kb{}
	for rows.Next() {
		var i Kb
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.ChunkingConfig,
			&i.EmbeddingModel,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIngestJob = `-- name: UpdateIngestJob :exec
UPDATE kb_ingest_jobs SET stage = $2, retries = $3, error = $4, finished_at = $5 WHERE id = $1
`

type UpdateIngestJobParams struct {
	ID         uuid.UUID
	Stage      string
	Retries    int32
	Error      pgtype.Text
	FinishedAt pgtype.Timestamptz
}

func (q *Queries) UpdateIngestJob(ctx context.Context, arg UpdateIngestJobParams) error {
	_, err := q.db.Exec(ctx, updateIngestJob,
		arg.ID,
		arg.Stage,
		arg.Retries,
		arg.Error,
		arg.FinishedAt,
	)
	return err
}

const updateKBStatus = `-- name: UpdateKBStatus :exec
UPDATE kbs SET status = $2, updated_at = now() WHERE id = $1
`

type UpdateKBStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdateKBStatus(ctx context.Context, arg UpdateKBStatusParams) error {
	_, err := q.db.Exec(ctx, updateKBStatus, arg.ID, arg.Status)
	return err
}

const upsertConnector = `-- name: UpsertConnector :exec
INSERT INTO connector_instances (id, kb_id, connector_kind, config_json, cursor, last_sync_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6, now())
ON CONFLICT (id) DO UPDATE
SET connector_kind = EXCLUDED.connector_kind, config_json = EXCLUDED.config_json,
    cursor = EXCLUDED.cursor, last_sync_at = EXCLUDED.last_sync_at
`

type UpsertConnectorParams struct {
	ID            uuid.UUID
	KbID          uuid.UUID
	ConnectorKind string
	ConfigJson    string
	Cursor        string
	LastSyncAt    pgtype.Timestamptz
}

func (q *Queries) UpsertConnector(ctx context.Context, arg UpsertConnectorParams) error {
	_, err := q.db.Exec(ctx, upsertConnector,
		arg.ID,
		arg.KbID,
		arg.ConnectorKind,
		arg.ConfigJson,
		arg.Cursor,
		arg.LastSyncAt,
	)
	return err
}

const upsertDocument = `-- name: UpsertDocument :exec
INSERT INTO kb_documents (id, kb_id, source_type, source_uri, hash, classification, status, ingested_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, now())
ON CONFLICT (id) DO UPDATE
SET source_type = EXCLUDED.source_type, source_uri = EXCLUDED.source_uri, hash = EXCLUDED.hash,
    classification = EXCLUDED.classification, status = EXCLUDED.status, ingested_at = EXCLUDED.ingested_at
`

type UpsertDocumentParams struct {
	ID             uuid.UUID
	KbID           uuid.UUID
	SourceType     string
	SourceUri      string
	Hash           string
	Classification string
	Status         string
	IngestedAt     pgtype.Timestamptz
}

func (q *Queries) UpsertDocument(ctx context.Context, arg UpsertDocumentParams) error {
	_, err := q.db.Exec(ctx, upsertDocument,
		arg.ID,
		arg.KbID,
		arg.SourceType,
		arg.SourceUri,
		arg.Hash,
		arg.Classification,
		arg.Status,
		arg.IngestedAt,
	)
	return err
}
