// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: llm_gateway.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProvider = `-- name: CreateProvider :one

INSERT INTO providers (id, kind, credential_ref, base_url, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, kind, credential_ref, base_url, status, workspace_id, name, api_key_ciphertext, created_by, created_at, updated_at
`

type CreateProviderParams struct {
	ID            uuid.UUID
	Kind          string
	CredentialRef string
	BaseUrl       string
	Status        string
}

// LLM Gateway:providers / model_aliases / routing_policies / model_call_logs
func (q *Queries) CreateProvider(ctx context.Context, arg CreateProviderParams) (Provider, error) {
	row := q.db.QueryRow(ctx, createProvider,
		arg.ID,
		arg.Kind,
		arg.CredentialRef,
		arg.BaseUrl,
		arg.Status,
	)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.CredentialRef,
		&i.BaseUrl,
		&i.Status,
		&i.WorkspaceID,
		&i.Name,
		&i.ApiKeyCiphertext,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRoutingPolicy = `-- name: CreateRoutingPolicy :one
INSERT INTO routing_policies (id, name, rules_json)
VALUES ($1, $2, $3)
RETURNING id, name, rules_json
`

type CreateRoutingPolicyParams struct {
	ID        uuid.UUID
	Name      string
	RulesJson []byte
}

func (q *Queries) CreateRoutingPolicy(ctx context.Context, arg CreateRoutingPolicyParams) (RoutingPolicy, error) {
	row := q.db.QueryRow(ctx, createRoutingPolicy, arg.ID, arg.Name, arg.RulesJson)
	var i RoutingPolicy
	err := row.Scan(&i.ID, &i.Name, &i.RulesJson)
	return i, err
}

const getModelAlias = `-- name: GetModelAlias :one
SELECT id, alias, provider_id, model_name, capabilities, classification_max FROM model_aliases WHERE alias = $1 LIMIT 1
`

func (q *Queries) GetModelAlias(ctx context.Context, alias string) (ModelAlias, error) {
	row := q.db.QueryRow(ctx, getModelAlias, alias)
	var i ModelAlias
	err := row.Scan(
		&i.ID,
		&i.Alias,
		&i.ProviderID,
		&i.ModelName,
		&i.Capabilities,
		&i.ClassificationMax,
	)
	return i, err
}

const insertModelCallLog = `-- name: InsertModelCallLog :exec
INSERT INTO model_call_logs (agent_id, user_id, provider_id, model, input_tokens, output_tokens, cached_tokens, cost, latency_ms, status, classification, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, now())
`

type InsertModelCallLogParams struct {
	AgentID        pgtype.UUID
	UserID         pgtype.UUID
	ProviderID     pgtype.UUID
	Model          string
	InputTokens    int32
	OutputTokens   int32
	CachedTokens   int32
	Cost           pgtype.Numeric
	LatencyMs      int32
	Status         string
	Classification string
}

func (q *Queries) InsertModelCallLog(ctx context.Context, arg InsertModelCallLogParams) error {
	_, err := q.db.Exec(ctx, insertModelCallLog,
		arg.AgentID,
		arg.UserID,
		arg.ProviderID,
		arg.Model,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CachedTokens,
		arg.Cost,
		arg.LatencyMs,
		arg.Status,
		arg.Classification,
	)
	return err
}

const listModelAliases = `-- name: ListModelAliases :many
SELECT id, alias, provider_id, model_name, capabilities, classification_max FROM model_aliases ORDER BY alias
`

func (q *Queries) ListModelAliases(ctx context.Context) ([]ModelAlias, error) {
	rows, err := q.db.Query(ctx, listModelAliases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModelAlias{}
	for rows.Next() {
		var i ModelAlias
		if err := rows.Scan(
			&i.ID,
			&i.Alias,
			&i.ProviderID,
			&i.ModelName,
			&i.Capabilities,
			&i.ClassificationMax,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviders = `-- name: ListProviders :many
SELECT id, kind, credential_ref, base_url, status, workspace_id, name, api_key_ciphertext, created_by, created_at, updated_at FROM providers ORDER BY kind
`

func (q *Queries) ListProviders(ctx context.Context) ([]Provider, error) {
	rows, err := q.db.Query(ctx, listProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Provider{}
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.CredentialRef,
			&i.BaseUrl,
			&i.Status,
			&i.WorkspaceID,
			&i.Name,
			&i.ApiKeyCiphertext,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertModelAlias = `-- name: UpsertModelAlias :one
INSERT INTO model_aliases (id, alias, provider_id, model_name, capabilities, classification_max)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (alias) DO UPDATE
SET provider_id = EXCLUDED.provider_id, model_name = EXCLUDED.model_name,
    capabilities = EXCLUDED.capabilities, classification_max = EXCLUDED.classification_max
RETURNING id, alias, provider_id, model_name, capabilities, classification_max
`

type UpsertModelAliasParams struct {
	ID                uuid.UUID
	Alias             string
	ProviderID        pgtype.UUID
	ModelName         string
	Capabilities      []byte
	ClassificationMax string
}

func (q *Queries) UpsertModelAlias(ctx context.Context, arg UpsertModelAliasParams) (ModelAlias, error) {
	row := q.db.QueryRow(ctx, upsertModelAlias,
		arg.ID,
		arg.Alias,
		arg.ProviderID,
		arg.ModelName,
		arg.Capabilities,
		arg.ClassificationMax,
	)
	var i ModelAlias
	err := row.Scan(
		&i.ID,
		&i.Alias,
		&i.ProviderID,
		&i.ModelName,
		&i.Capabilities,
		&i.ClassificationMax,
	)
	return i, err
}
