// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package pgstore

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddEvalCase(ctx context.Context, arg AddEvalCaseParams) (EvalCase, error)
	AddEvalScore(ctx context.Context, arg AddEvalScoreParams) error
	BeginApprovalExecution(ctx context.Context, arg BeginApprovalExecutionParams) (Approval, error)
	CompleteApprovalExecution(ctx context.Context, arg CompleteApprovalExecutionParams) (int64, error)
	CompleteToolInvocation(ctx context.Context, arg CompleteToolInvocationParams) (int64, error)
	ConsumeQuota(ctx context.Context, arg ConsumeQuotaParams) (QuotaLedger, error)
	CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error)
	CreateAgentVersion(ctx context.Context, arg CreateAgentVersionParams) (AgentVersion, error)
	CreateAgentVersionAndBindDev(ctx context.Context, arg CreateAgentVersionAndBindDevParams) error
	CreateAgentWithVersion(ctx context.Context, arg CreateAgentWithVersionParams) error
	CreateApproval(ctx context.Context, arg CreateApprovalParams) (Approval, error)
	CreateCheckpoint(ctx context.Context, arg CreateCheckpointParams) error
	CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error)
	CreateDeadLetter(ctx context.Context, arg CreateDeadLetterParams) (DeadLetter, error)
	CreateEvalDataset(ctx context.Context, arg CreateEvalDatasetParams) (EvalDataset, error)
	CreateEvalRun(ctx context.Context, arg CreateEvalRunParams) (EvalRun, error)
	CreateGuardRule(ctx context.Context, arg CreateGuardRuleParams) (GuardRule, error)
	CreateIngestJob(ctx context.Context, arg CreateIngestJobParams) error
	// Jobs:jobs / job_schedules / dead_letters
	CreateJob(ctx context.Context, arg CreateJobParams) (Job, error)
	CreateJobSchedule(ctx context.Context, arg CreateJobScheduleParams) (JobSchedule, error)
	CreateKB(ctx context.Context, arg CreateKBParams) (Kb, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreatePrompt(ctx context.Context, arg CreatePromptParams) (Prompt, error)
	CreatePromptVersion(ctx context.Context, arg CreatePromptVersionParams) (PromptVersion, error)
	// LLM Gateway:providers / model_aliases / routing_policies / model_call_logs
	CreateProvider(ctx context.Context, arg CreateProviderParams) (Provider, error)
	CreateRoutingPolicy(ctx context.Context, arg CreateRoutingPolicyParams) (RoutingPolicy, error)
	CreateSandboxExecution(ctx context.Context, arg CreateSandboxExecutionParams) error
	CreateSkill(ctx context.Context, arg CreateSkillParams) (Skill, error)
	CreateSkillSubscription(ctx context.Context, arg CreateSkillSubscriptionParams) error
	CreateSkillVersion(ctx context.Context, arg CreateSkillVersionParams) (SkillVersion, error)
	CreateSkillWithVersion(ctx context.Context, arg CreateSkillWithVersionParams) error
	CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error)
	CreateTeamVersion(ctx context.Context, arg CreateTeamVersionParams) (TeamVersion, error)
	CreateTeamVersionAndBindDev(ctx context.Context, arg CreateTeamVersionAndBindDevParams) error
	CreateTeamWithVersion(ctx context.Context, arg CreateTeamWithVersionParams) error
	CreateTool(ctx context.Context, arg CreateToolParams) (Tool, error)
	CreateToolInvocation(ctx context.Context, arg CreateToolInvocationParams) error
	CreateToolTestRun(ctx context.Context, arg CreateToolTestRunParams) (ToolTestRun, error)
	CreateToolVersion(ctx context.Context, arg CreateToolVersionParams) (ToolVersion, error)
	CreateToolWithVersion(ctx context.Context, arg CreateToolWithVersionParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error)
	CreateWorkspaceWithOwner(ctx context.Context, arg CreateWorkspaceWithOwnerParams) error
	DeleteWorkspaceMember(ctx context.Context, arg DeleteWorkspaceMemberParams) (int64, error)
	EncryptToolVersionAuth(ctx context.Context, arg EncryptToolVersionAuthParams) error
	FailApprovalExecution(ctx context.Context, arg FailApprovalExecutionParams) (int64, error)
	GetActiveExperiment(ctx context.Context, arg GetActiveExperimentParams) (PromptExperiment, error)
	// Agent:agents / agent_versions / agent_envs
	// 「当前版本」走 env 指针(agent_envs);CreateAgentVersion 由 store 自动把新版本绑到 dev(对齐 memory 语义)。
	GetAgent(ctx context.Context, id uuid.UUID) (Agent, error)
	GetAgentCurrentVersion(ctx context.Context, arg GetAgentCurrentVersionParams) (AgentVersion, error)
	GetAgentVersion(ctx context.Context, id uuid.UUID) (AgentVersion, error)
	GetApproval(ctx context.Context, id uuid.UUID) (Approval, error)
	GetCheckpointForApproval(ctx context.Context, arg GetCheckpointForApprovalParams) (Checkpoint, error)
	// Conversation:conversations / messages(agent.Store 的会话部分)
	GetConversation(ctx context.Context, id uuid.UUID) (Conversation, error)
	GetDocument(ctx context.Context, id uuid.UUID) (KbDocument, error)
	// Eval:eval_datasets / eval_cases / eval_runs / eval_scores
	GetEvalDataset(ctx context.Context, id uuid.UUID) (EvalDataset, error)
	GetEvalRun(ctx context.Context, id uuid.UUID) (EvalRun, error)
	GetGuardRule(ctx context.Context, id uuid.UUID) (GuardRule, error)
	GetJob(ctx context.Context, id uuid.UUID) (Job, error)
	// KB:kbs / kb_documents / kb_ingest_jobs / connector_instances
	// kb_chunks 的写入与向量/全文检索由 runtime/retriever 的 PostgreSQL 实现负责。
	GetKB(ctx context.Context, id uuid.UUID) (Kb, error)
	GetModelAlias(ctx context.Context, alias string) (ModelAlias, error)
	// Prompt:prompts / prompt_versions / prompt_envs / prompt_experiments
	GetPrompt(ctx context.Context, id uuid.UUID) (Prompt, error)
	GetPromptEnv(ctx context.Context, arg GetPromptEnvParams) (uuid.UUID, error)
	GetPromptVersion(ctx context.Context, id uuid.UUID) (PromptVersion, error)
	GetPromptVersionByNumber(ctx context.Context, arg GetPromptVersionByNumberParams) (PromptVersion, error)
	GetQuota(ctx context.Context, arg GetQuotaParams) (QuotaLedger, error)
	// Skill:skills / skill_versions / skill_subscriptions
	GetSkill(ctx context.Context, id uuid.UUID) (Skill, error)
	GetSkillVersion(ctx context.Context, id uuid.UUID) (SkillVersion, error)
	// Team: teams / team_versions / team_envs
	GetTeam(ctx context.Context, id uuid.UUID) (Team, error)
	GetTeamCurrentVersion(ctx context.Context, arg GetTeamCurrentVersionParams) (TeamVersion, error)
	GetTeamVersion(ctx context.Context, id uuid.UUID) (TeamVersion, error)
	// Tool:tools / tool_versions / tool_test_runs
	GetTool(ctx context.Context, id uuid.UUID) (Tool, error)
	// 「当前版本」= 版本号最大者(memory 版 CreateToolVersion 把最新创建设为 current,版本号单调递增故等价)。
	GetToolCurrentVersion(ctx context.Context, toolID uuid.UUID) (ToolVersion, error)
	GetToolLastSuccessfulTestRun(ctx context.Context, toolID uuid.UUID) (ToolTestRun, error)
	GetToolLastSuccessfulTestRunForVersion(ctx context.Context, toolVersionID uuid.UUID) (ToolTestRun, error)
	GetToolLatestPublishedVersion(ctx context.Context, toolID uuid.UUID) (ToolVersion, error)
	GetToolVersion(ctx context.Context, id uuid.UUID) (ToolVersion, error)
	// IAM: users and workspaces
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetWorkspaceByID(ctx context.Context, id string) (Workspace, error)
	GetWorkspaceMember(ctx context.Context, arg GetWorkspaceMemberParams) (GetWorkspaceMemberRow, error)
	// Audit:audit_logs(分区父表,查询透明走分区)
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error
	InsertInjectionLog(ctx context.Context, arg InsertInjectionLogParams) (InjectionLog, error)
	InsertModelCallLog(ctx context.Context, arg InsertModelCallLogParams) error
	InsertSkillTrigger(ctx context.Context, arg InsertSkillTriggerParams) error
	ListAgentVersions(ctx context.Context, agentID uuid.UUID) ([]AgentVersion, error)
	ListAgents(ctx context.Context, workspaceID string) ([]Agent, error)
	ListApprovalsByConversation(ctx context.Context, conversationID pgtype.UUID) ([]Approval, error)
	ListConnectors(ctx context.Context, kbID uuid.UUID) ([]ConnectorInstance, error)
	ListConversations(ctx context.Context, arg ListConversationsParams) ([]Conversation, error)
	ListDocuments(ctx context.Context, kbID uuid.UUID) ([]KbDocument, error)
	ListEnabledSchedules(ctx context.Context) ([]JobSchedule, error)
	ListEvalCases(ctx context.Context, datasetID uuid.UUID) ([]EvalCase, error)
	ListEvalDatasets(ctx context.Context, workspaceID string) ([]EvalDataset, error)
	ListEvalRuns(ctx context.Context, datasetID uuid.UUID) ([]EvalRun, error)
	ListEvalScores(ctx context.Context, runID uuid.UUID) ([]EvalScore, error)
	// Guard:guard_rules / injection_logs / quota_ledger / approvals
	ListGuardRules(ctx context.Context, workspaceID string) ([]GuardRule, error)
	ListIngestJobs(ctx context.Context, kbID uuid.UUID) ([]KbIngestJob, error)
	ListInjectionLogs(ctx context.Context, conversationID pgtype.UUID) ([]InjectionLog, error)
	ListKBs(ctx context.Context, workspaceID string) ([]Kb, error)
	ListLegacyToolAuthVersions(ctx context.Context) ([]ToolVersion, error)
	ListMessages(ctx context.Context, conversationID uuid.UUID) ([]Message, error)
	ListModelAliases(ctx context.Context) ([]ModelAlias, error)
	ListPendingApprovals(ctx context.Context, workspaceID string) ([]Approval, error)
	ListPendingJobs(ctx context.Context, limit int32) ([]Job, error)
	ListPromptVersions(ctx context.Context, promptID uuid.UUID) ([]PromptVersion, error)
	ListPrompts(ctx context.Context, workspaceID string) ([]Prompt, error)
	ListProviders(ctx context.Context) ([]Provider, error)
	ListReadyApprovalResumes(ctx context.Context, limit int32) ([]Approval, error)
	ListSkillVersions(ctx context.Context, skillID uuid.UUID) ([]SkillVersion, error)
	ListSkills(ctx context.Context, workspaceID string) ([]Skill, error)
	ListSubscriptionsForAgent(ctx context.Context, agentID string) ([]SkillSubscription, error)
	ListTeamVersions(ctx context.Context, teamID uuid.UUID) ([]TeamVersion, error)
	ListTeams(ctx context.Context, workspaceID string) ([]Team, error)
	ListToolVersions(ctx context.Context, toolID uuid.UUID) ([]ToolVersion, error)
	ListTools(ctx context.Context, workspaceID string) ([]Tool, error)
	ListUserWorkspaces(ctx context.Context, arg ListUserWorkspacesParams) ([]Workspace, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	ListWorkspaceMembers(ctx context.Context, workspaceID string) ([]ListWorkspaceMembersRow, error)
	ListWorkspaceQuotas(ctx context.Context, arg ListWorkspaceQuotasParams) ([]QuotaLedger, error)
	ListWorkspaces(ctx context.Context, arg ListWorkspacesParams) ([]Workspace, error)
	// QueryAuditLogs:可选过滤(actor / resource_type / conversation),倒序最新优先。
	// limit 为 0 时 NULLIF→NULL,即不限制(对齐 memory 版 Limit<=0 返回全部)。
	QueryAuditLogs(ctx context.Context, arg QueryAuditLogsParams) ([]AuditLog, error)
	RenewApprovalExecution(ctx context.Context, arg RenewApprovalExecutionParams) (int64, error)
	ResolvePendingApproval(ctx context.Context, arg ResolvePendingApprovalParams) (Approval, error)
	SetQuotaLimit(ctx context.Context, arg SetQuotaLimitParams) (QuotaLedger, error)
	SetUserRole(ctx context.Context, arg SetUserRoleParams) error
	UpdateGuardRule(ctx context.Context, arg UpdateGuardRuleParams) (GuardRule, error)
	UpdateIngestJob(ctx context.Context, arg UpdateIngestJobParams) error
	UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) error
	UpdateKBStatus(ctx context.Context, arg UpdateKBStatusParams) error
	UpdateSkillVersionStatus(ctx context.Context, arg UpdateSkillVersionStatusParams) error
	UpdateToolVersionStatus(ctx context.Context, arg UpdateToolVersionStatusParams) error
	UpsertAgentEnv(ctx context.Context, arg UpsertAgentEnvParams) error
	UpsertConnector(ctx context.Context, arg UpsertConnectorParams) error
	UpsertDocument(ctx context.Context, arg UpsertDocumentParams) error
	UpsertExperiment(ctx context.Context, arg UpsertExperimentParams) error
	UpsertModelAlias(ctx context.Context, arg UpsertModelAliasParams) (ModelAlias, error)
	UpsertPromptEnv(ctx context.Context, arg UpsertPromptEnvParams) error
	UpsertTeamEnv(ctx context.Context, arg UpsertTeamEnvParams) error
	UpsertWorkspaceMember(ctx context.Context, arg UpsertWorkspaceMemberParams) (WorkspaceMember, error)
}

var _ Querier = (*Queries)(nil)
