// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: skill.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
)

const createSkill = `-- name: CreateSkill :one
INSERT INTO skills (id, workspace_id, name, category, created_by, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, now(), now())
RETURNING id, workspace_id, name, category, created_by, created_at, updated_at
`

type CreateSkillParams struct {
	ID          uuid.UUID
	WorkspaceID string
	Name        string
	Category    string
	CreatedBy   string
}

func (q *Queries) CreateSkill(ctx context.Context, arg CreateSkillParams) (Skill, error) {
	row := q.db.QueryRow(ctx, createSkill,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Category,
		arg.CreatedBy,
	)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Category,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSkillSubscription = `-- name: CreateSkillSubscription :exec
INSERT INTO skill_subscriptions (skill_id, version_id, agent_id, workspace_id)
VALUES ($1, $2, $3, $4)
`

type CreateSkillSubscriptionParams struct {
	SkillID     uuid.UUID
	VersionID   uuid.UUID
	AgentID     string
	WorkspaceID string
}

func (q *Queries) CreateSkillSubscription(ctx context.Context, arg CreateSkillSubscriptionParams) error {
	_, err := q.db.Exec(ctx, createSkillSubscription,
		arg.SkillID,
		arg.VersionID,
		arg.AgentID,
		arg.WorkspaceID,
	)
	return err
}

const createSkillVersion = `-- name: CreateSkillVersion :one
INSERT INTO skill_versions (id, skill_id, version, frontmatter_json, body_md, status, created_by, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, now())
RETURNING id, skill_id, version, frontmatter_json, body_md, status, created_by, created_at
`

type CreateSkillVersionParams struct {
	ID              uuid.UUID
	SkillID         uuid.UUID
	Version         int32
	FrontmatterJson string
	BodyMd          string
	Status          string
	CreatedBy       string
}

func (q *Queries) CreateSkillVersion(ctx context.Context, arg CreateSkillVersionParams) (SkillVersion, error) {
	row := q.db.QueryRow(ctx, createSkillVersion,
		arg.ID,
		arg.SkillID,
		arg.Version,
		arg.FrontmatterJson,
		arg.BodyMd,
		arg.Status,
		arg.CreatedBy,
	)
	var i SkillVersion
	err := row.Scan(
		&i.ID,
		&i.SkillID,
		&i.Version,
		&i.FrontmatterJson,
		&i.BodyMd,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createSkillWithVersion = `-- name: CreateSkillWithVersion :exec
WITH inserted_skill AS (
  INSERT INTO skills (id, workspace_id, name, category, created_by, created_at, updated_at)
  VALUES ($6, $7, $8, $9, $10, now(), now())
  RETURNING id
)
INSERT INTO skill_versions (id, skill_id, version, frontmatter_json, body_md, status, created_by, created_at)
SELECT $1, id, 1, $2, $3, $4,
       $5, now()
FROM inserted_skill
`

type CreateSkillWithVersionParams struct {
	VersionID        uuid.UUID
	FrontmatterJson  string
	BodyMd           string
	VersionStatus    string
	VersionCreatedBy string
	SkillID          uuid.UUID
	WorkspaceID      string
	Name             string
	Category         string
	SkillCreatedBy   string
}

func (q *Queries) CreateSkillWithVersion(ctx context.Context, arg CreateSkillWithVersionParams) error {
	_, err := q.db.Exec(ctx, createSkillWithVersion,
		arg.VersionID,
		arg.FrontmatterJson,
		arg.BodyMd,
		arg.VersionStatus,
		arg.VersionCreatedBy,
		arg.SkillID,
		arg.WorkspaceID,
		arg.Name,
		arg.Category,
		arg.SkillCreatedBy,
	)
	return err
}

const getSkill = `-- name: GetSkill :one

SELECT id, workspace_id, name, category, created_by, created_at, updated_at FROM skills WHERE id = $1 LIMIT 1
`

// Skill:skills / skill_versions / skill_subscriptions
func (q *Queries) GetSkill(ctx context.Context, id uuid.UUID) (Skill, error) {
	row := q.db.QueryRow(ctx, getSkill, id)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Category,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSkillVersion = `-- name: GetSkillVersion :one
SELECT id, skill_id, version, frontmatter_json, body_md, status, created_by, created_at FROM skill_versions WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSkillVersion(ctx context.Context, id uuid.UUID) (SkillVersion, error) {
	row := q.db.QueryRow(ctx, getSkillVersion, id)
	var i SkillVersion
	err := row.Scan(
		&i.ID,
		&i.SkillID,
		&i.Version,
		&i.FrontmatterJson,
		&i.BodyMd,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listSkillVersions = `-- name: ListSkillVersions :many
SELECT id, skill_id, version, frontmatter_json, body_md, status, created_by, created_at FROM skill_versions WHERE skill_id = $1 ORDER BY version
`

func (q *Queries) ListSkillVersions(ctx context.Context, skillID uuid.UUID) ([]SkillVersion, error) {
	rows, err := q.db.Query(ctx, listSkillVersions, skillID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SkillVersion{}
	for rows.Next() {
		var i SkillVersion
		if err := rows.Scan(
			&i.ID,
			&i.SkillID,
			&i.Version,
			&i.FrontmatterJson,
			&i.BodyMd,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkills = `-- name: ListSkills :many
SELECT id, workspace_id, name, category, created_by, created_at, updated_at FROM skills WHERE workspace_id = $1 ORDER BY created_at
`

func (q *Queries) ListSkills(ctx context.Context, workspaceID string) ([]Skill, error) {
	rows, err := q.db.Query(ctx, listSkills, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Skill{}
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Category,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionsForAgent = `-- name: ListSubscriptionsForAgent :many
SELECT id, skill_id, version_id, agent_id, workspace_id, created_at FROM skill_subscriptions WHERE agent_id = $1 ORDER BY id
`

func (q *Queries) ListSubscriptionsForAgent(ctx context.Context, agentID string) ([]SkillSubscription, error) {
	rows, err := q.db.Query(ctx, listSubscriptionsForAgent, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SkillSubscription{}
	for rows.Next() {
		var i SkillSubscription
		if err := rows.Scan(
			&i.ID,
			&i.SkillID,
			&i.VersionID,
			&i.AgentID,
			&i.WorkspaceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSkillVersionStatus = `-- name: UpdateSkillVersionStatus :exec
UPDATE skill_versions SET status = $2 WHERE id = $1
`

type UpdateSkillVersionStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdateSkillVersionStatus(ctx context.Context, arg UpdateSkillVersionStatusParams) error {
	_, err := q.db.Exec(ctx, updateSkillVersionStatus, arg.ID, arg.Status)
	return err
}
