// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: team.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
)

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (id, workspace_id, name, mode, created_at)
VALUES ($1, $2, $3, $4, now())
RETURNING id, workspace_id, name, mode, created_at
`

type CreateTeamParams struct {
	ID          uuid.UUID
	WorkspaceID string
	Name        string
	Mode        string
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Mode,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Mode,
		&i.CreatedAt,
	)
	return i, err
}

const createTeamVersion = `-- name: CreateTeamVersion :one
INSERT INTO team_versions (id, team_id, version, snapshot_json, created_at)
VALUES ($1, $2, $3, $4, now())
RETURNING id, team_id, version, snapshot_json, created_at
`

type CreateTeamVersionParams struct {
	ID           uuid.UUID
	TeamID       uuid.UUID
	Version      int32
	SnapshotJson string
}

func (q *Queries) CreateTeamVersion(ctx context.Context, arg CreateTeamVersionParams) (TeamVersion, error) {
	row := q.db.QueryRow(ctx, createTeamVersion,
		arg.ID,
		arg.TeamID,
		arg.Version,
		arg.SnapshotJson,
	)
	var i TeamVersion
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Version,
		&i.SnapshotJson,
		&i.CreatedAt,
	)
	return i, err
}

const createTeamVersionAndBindDev = `-- name: CreateTeamVersionAndBindDev :exec
WITH inserted_version AS (
  INSERT INTO team_versions (id, team_id, version, snapshot_json, created_at)
  VALUES ($1, $2, $3, $4, now())
  RETURNING id, team_id
)
INSERT INTO team_envs (team_id, env, version_id)
SELECT team_id, 'dev', id FROM inserted_version
ON CONFLICT (team_id, env) DO UPDATE SET version_id=EXCLUDED.version_id
`

type CreateTeamVersionAndBindDevParams struct {
	VersionID    uuid.UUID
	TeamID       uuid.UUID
	Version      int32
	SnapshotJson string
}

func (q *Queries) CreateTeamVersionAndBindDev(ctx context.Context, arg CreateTeamVersionAndBindDevParams) error {
	_, err := q.db.Exec(ctx, createTeamVersionAndBindDev,
		arg.VersionID,
		arg.TeamID,
		arg.Version,
		arg.SnapshotJson,
	)
	return err
}

const createTeamWithVersion = `-- name: CreateTeamWithVersion :exec
WITH inserted_team AS (
  INSERT INTO teams (id, workspace_id, name, mode, created_at)
  VALUES ($1, $2, $3, $4, now())
  RETURNING id
), inserted_version AS (
  INSERT INTO team_versions (id, team_id, version, snapshot_json, created_at)
  SELECT $5, id, 1, $6, now() FROM inserted_team
  RETURNING id, team_id
)
INSERT INTO team_envs (team_id, env, version_id)
SELECT team_id, 'dev', id FROM inserted_version
`

type CreateTeamWithVersionParams struct {
	TeamID       uuid.UUID
	WorkspaceID  string
	Name         string
	Mode         string
	VersionID    uuid.UUID
	SnapshotJson string
}

func (q *Queries) CreateTeamWithVersion(ctx context.Context, arg CreateTeamWithVersionParams) error {
	_, err := q.db.Exec(ctx, createTeamWithVersion,
		arg.TeamID,
		arg.WorkspaceID,
		arg.Name,
		arg.Mode,
		arg.VersionID,
		arg.SnapshotJson,
	)
	return err
}

const getTeam = `-- name: GetTeam :one

SELECT id, workspace_id, name, mode, created_at FROM teams WHERE id = $1 LIMIT 1
`

// Team: teams / team_versions / team_envs
func (q *Queries) GetTeam(ctx context.Context, id uuid.UUID) (Team, error) {
	row := q.db.QueryRow(ctx, getTeam, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Mode,
		&i.CreatedAt,
	)
	return i, err
}

const getTeamCurrentVersion = `-- name: GetTeamCurrentVersion :one
SELECT tv.id, tv.team_id, tv.version, tv.snapshot_json, tv.created_at FROM team_versions tv
JOIN team_envs te ON te.version_id = tv.id
WHERE te.team_id = $1 AND te.env = $2
LIMIT 1
`

type GetTeamCurrentVersionParams struct {
	TeamID uuid.UUID
	Env    string
}

func (q *Queries) GetTeamCurrentVersion(ctx context.Context, arg GetTeamCurrentVersionParams) (TeamVersion, error) {
	row := q.db.QueryRow(ctx, getTeamCurrentVersion, arg.TeamID, arg.Env)
	var i TeamVersion
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Version,
		&i.SnapshotJson,
		&i.CreatedAt,
	)
	return i, err
}

const getTeamVersion = `-- name: GetTeamVersion :one
SELECT id, team_id, version, snapshot_json, created_at FROM team_versions WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTeamVersion(ctx context.Context, id uuid.UUID) (TeamVersion, error) {
	row := q.db.QueryRow(ctx, getTeamVersion, id)
	var i TeamVersion
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Version,
		&i.SnapshotJson,
		&i.CreatedAt,
	)
	return i, err
}

const listTeamVersions = `-- name: ListTeamVersions :many
SELECT id, team_id, version, snapshot_json, created_at FROM team_versions WHERE team_id = $1 ORDER BY version DESC
`

func (q *Queries) ListTeamVersions(ctx context.Context, teamID uuid.UUID) ([]TeamVersion, error) {
	rows, err := q.db.Query(ctx, listTeamVersions, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TeamVersion{}
	for rows.Next() {
		var i TeamVersion
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Version,
			&i.SnapshotJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeams = `-- name: ListTeams :many
SELECT id, workspace_id, name, mode, created_at FROM teams WHERE workspace_id = $1 ORDER BY created_at
`

func (q *Queries) ListTeams(ctx context.Context, workspaceID string) ([]Team, error) {
	rows, err := q.db.Query(ctx, listTeams, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Team{}
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Mode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTeamEnv = `-- name: UpsertTeamEnv :exec
INSERT INTO team_envs (team_id, env, version_id)
VALUES ($1, $2, $3)
ON CONFLICT (team_id, env) DO UPDATE SET version_id = EXCLUDED.version_id
`

type UpsertTeamEnvParams struct {
	TeamID    uuid.UUID
	Env       string
	VersionID uuid.UUID
}

func (q *Queries) UpsertTeamEnv(ctx context.Context, arg UpsertTeamEnvParams) error {
	_, err := q.db.Exec(ctx, upsertTeamEnv, arg.TeamID, arg.Env, arg.VersionID)
	return err
}
