// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tool.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeToolInvocation = `-- name: CompleteToolInvocation :execrows
UPDATE tool_invocations
SET result = $2, status = $3, latency_ms = $4, error = $5
WHERE id = $1 AND status = 'running'
`

type CompleteToolInvocationParams struct {
	ID        uuid.UUID
	Result    []byte
	Status    string
	LatencyMs int32
	Error     string
}

func (q *Queries) CompleteToolInvocation(ctx context.Context, arg CompleteToolInvocationParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeToolInvocation,
		arg.ID,
		arg.Result,
		arg.Status,
		arg.LatencyMs,
		arg.Error,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createSandboxExecution = `-- name: CreateSandboxExecution :exec
INSERT INTO sandbox_executions (
    id, workspace_id, conversation_id, invocation_id, tool_version_id, tool_call_id,
    execution_id, language, container_id, exit_code, stdout, stderr,
    resource_usage, duration_ms, timed_out, output_truncated, status, created_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12,
        '{}', $13, $14, $15, $16, now())
`

type CreateSandboxExecutionParams struct {
	ID              uuid.UUID
	WorkspaceID     string
	ConversationID  pgtype.UUID
	InvocationID    pgtype.UUID
	ToolVersionID   pgtype.UUID
	ToolCallID      string
	ExecutionID     string
	Language        string
	ContainerID     string
	ExitCode        pgtype.Int4
	Stdout          string
	Stderr          string
	DurationMs      int64
	TimedOut        bool
	OutputTruncated bool
	Status          string
}

func (q *Queries) CreateSandboxExecution(ctx context.Context, arg CreateSandboxExecutionParams) error {
	_, err := q.db.Exec(ctx, createSandboxExecution,
		arg.ID,
		arg.WorkspaceID,
		arg.ConversationID,
		arg.InvocationID,
		arg.ToolVersionID,
		arg.ToolCallID,
		arg.ExecutionID,
		arg.Language,
		arg.ContainerID,
		arg.ExitCode,
		arg.Stdout,
		arg.Stderr,
		arg.DurationMs,
		arg.TimedOut,
		arg.OutputTruncated,
		arg.Status,
	)
	return err
}

const createTool = `-- name: CreateTool :one
INSERT INTO tools (id, workspace_id, name, description, source_type, sensitive, classification_max, created_by, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, now(), now())
RETURNING id, workspace_id, name, description, source_type, sensitive, classification_max, created_by, created_at, updated_at
`

type CreateToolParams struct {
	ID                uuid.UUID
	WorkspaceID       string
	Name              string
	Description       string
	SourceType        string
	Sensitive         bool
	ClassificationMax string
	CreatedBy         string
}

func (q *Queries) CreateTool(ctx context.Context, arg CreateToolParams) (Tool, error) {
	row := q.db.QueryRow(ctx, createTool,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Description,
		arg.SourceType,
		arg.Sensitive,
		arg.ClassificationMax,
		arg.CreatedBy,
	)
	var i Tool
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.SourceType,
		&i.Sensitive,
		&i.ClassificationMax,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createToolInvocation = `-- name: CreateToolInvocation :exec
INSERT INTO tool_invocations (
    id, workspace_id, conversation_id, tool_call_id, tool_version_id,
    args, result, status, latency_ms, error, created_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, now())
`

type CreateToolInvocationParams struct {
	ID             uuid.UUID
	WorkspaceID    string
	ConversationID pgtype.UUID
	ToolCallID     string
	ToolVersionID  pgtype.UUID
	Args           []byte
	Result         []byte
	Status         string
	LatencyMs      int32
	Error          string
}

func (q *Queries) CreateToolInvocation(ctx context.Context, arg CreateToolInvocationParams) error {
	_, err := q.db.Exec(ctx, createToolInvocation,
		arg.ID,
		arg.WorkspaceID,
		arg.ConversationID,
		arg.ToolCallID,
		arg.ToolVersionID,
		arg.Args,
		arg.Result,
		arg.Status,
		arg.LatencyMs,
		arg.Error,
	)
	return err
}

const createToolTestRun = `-- name: CreateToolTestRun :one
INSERT INTO tool_test_runs (id, tool_id, tool_version_id, input, output, status, latency_ms, error, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, now())
RETURNING id, tool_id, input, output, status, latency_ms, error, created_at, tool_version_id
`

type CreateToolTestRunParams struct {
	ID            uuid.UUID
	ToolID        uuid.UUID
	ToolVersionID uuid.UUID
	Input         string
	Output        string
	Status        string
	LatencyMs     int32
	Error         pgtype.Text
}

func (q *Queries) CreateToolTestRun(ctx context.Context, arg CreateToolTestRunParams) (ToolTestRun, error) {
	row := q.db.QueryRow(ctx, createToolTestRun,
		arg.ID,
		arg.ToolID,
		arg.ToolVersionID,
		arg.Input,
		arg.Output,
		arg.Status,
		arg.LatencyMs,
		arg.Error,
	)
	var i ToolTestRun
	err := row.Scan(
		&i.ID,
		&i.ToolID,
		&i.Input,
		&i.Output,
		&i.Status,
		&i.LatencyMs,
		&i.Error,
		&i.CreatedAt,
		&i.ToolVersionID,
	)
	return i, err
}

const createToolVersion = `-- name: CreateToolVersion :one
INSERT INTO tool_versions (id, tool_id, version, schema_json, endpoint_config, auth_config, auth_config_encrypted, retry_policy, status, created_by, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, now())
RETURNING id, tool_id, version, schema_json, endpoint_config, auth_config, retry_policy, status, created_by, created_at, auth_config_encrypted
`

type CreateToolVersionParams struct {
	ID                  uuid.UUID
	ToolID              uuid.UUID
	Version             int32
	SchemaJson          string
	EndpointConfig      string
	AuthConfig          string
	AuthConfigEncrypted []byte
	RetryPolicy         string
	Status              string
	CreatedBy           string
}

func (q *Queries) CreateToolVersion(ctx context.Context, arg CreateToolVersionParams) (ToolVersion, error) {
	row := q.db.QueryRow(ctx, createToolVersion,
		arg.ID,
		arg.ToolID,
		arg.Version,
		arg.SchemaJson,
		arg.EndpointConfig,
		arg.AuthConfig,
		arg.AuthConfigEncrypted,
		arg.RetryPolicy,
		arg.Status,
		arg.CreatedBy,
	)
	var i ToolVersion
	err := row.Scan(
		&i.ID,
		&i.ToolID,
		&i.Version,
		&i.SchemaJson,
		&i.EndpointConfig,
		&i.AuthConfig,
		&i.RetryPolicy,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.AuthConfigEncrypted,
	)
	return i, err
}

const createToolWithVersion = `-- name: CreateToolWithVersion :exec
WITH inserted_tool AS (
  INSERT INTO tools (id, workspace_id, name, description, source_type, sensitive, classification_max, created_by, created_at, updated_at)
  VALUES ($9, $10, $11, $12, $13,
          $14, $15, $16, now(), now())
  RETURNING id
)
INSERT INTO tool_versions
  (id, tool_id, version, schema_json, endpoint_config, auth_config, auth_config_encrypted, retry_policy, status, created_by, created_at)
SELECT $1, id, 1, $2, $3, $4,
       $5, $6, $7, $8, now()
FROM inserted_tool
`

type CreateToolWithVersionParams struct {
	VersionID           uuid.UUID
	SchemaJson          string
	EndpointConfig      string
	AuthConfig          string
	AuthConfigEncrypted []byte
	RetryPolicy         string
	VersionStatus       string
	VersionCreatedBy    string
	ToolID              uuid.UUID
	WorkspaceID         string
	Name                string
	Description         string
	SourceType          string
	Sensitive           bool
	ClassificationMax   string
	ToolCreatedBy       string
}

func (q *Queries) CreateToolWithVersion(ctx context.Context, arg CreateToolWithVersionParams) error {
	_, err := q.db.Exec(ctx, createToolWithVersion,
		arg.VersionID,
		arg.SchemaJson,
		arg.EndpointConfig,
		arg.AuthConfig,
		arg.AuthConfigEncrypted,
		arg.RetryPolicy,
		arg.VersionStatus,
		arg.VersionCreatedBy,
		arg.ToolID,
		arg.WorkspaceID,
		arg.Name,
		arg.Description,
		arg.SourceType,
		arg.Sensitive,
		arg.ClassificationMax,
		arg.ToolCreatedBy,
	)
	return err
}

const encryptToolVersionAuth = `-- name: EncryptToolVersionAuth :exec
UPDATE tool_versions
SET auth_config = '{}', auth_config_encrypted = $2
WHERE id = $1 AND auth_config_encrypted IS NULL
`

type EncryptToolVersionAuthParams struct {
	ID                  uuid.UUID
	AuthConfigEncrypted []byte
}

func (q *Queries) EncryptToolVersionAuth(ctx context.Context, arg EncryptToolVersionAuthParams) error {
	_, err := q.db.Exec(ctx, encryptToolVersionAuth, arg.ID, arg.AuthConfigEncrypted)
	return err
}

const getTool = `-- name: GetTool :one

SELECT id, workspace_id, name, description, source_type, sensitive, classification_max, created_by, created_at, updated_at FROM tools WHERE id = $1 LIMIT 1
`

// Tool:tools / tool_versions / tool_test_runs
func (q *Queries) GetTool(ctx context.Context, id uuid.UUID) (Tool, error) {
	row := q.db.QueryRow(ctx, getTool, id)
	var i Tool
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.SourceType,
		&i.Sensitive,
		&i.ClassificationMax,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getToolCurrentVersion = `-- name: GetToolCurrentVersion :one
SELECT id, tool_id, version, schema_json, endpoint_config, auth_config, retry_policy, status, created_by, created_at, auth_config_encrypted FROM tool_versions WHERE tool_id = $1 ORDER BY version DESC LIMIT 1
`

// 「当前版本」= 版本号最大者(memory 版 CreateToolVersion 把最新创建设为 current,版本号单调递增故等价)。
func (q *Queries) GetToolCurrentVersion(ctx context.Context, toolID uuid.UUID) (ToolVersion, error) {
	row := q.db.QueryRow(ctx, getToolCurrentVersion, toolID)
	var i ToolVersion
	err := row.Scan(
		&i.ID,
		&i.ToolID,
		&i.Version,
		&i.SchemaJson,
		&i.EndpointConfig,
		&i.AuthConfig,
		&i.RetryPolicy,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.AuthConfigEncrypted,
	)
	return i, err
}

const getToolLastSuccessfulTestRun = `-- name: GetToolLastSuccessfulTestRun :one
SELECT id, tool_id, input, output, status, latency_ms, error, created_at, tool_version_id FROM tool_test_runs WHERE tool_id = $1 AND status = 'success' ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetToolLastSuccessfulTestRun(ctx context.Context, toolID uuid.UUID) (ToolTestRun, error) {
	row := q.db.QueryRow(ctx, getToolLastSuccessfulTestRun, toolID)
	var i ToolTestRun
	err := row.Scan(
		&i.ID,
		&i.ToolID,
		&i.Input,
		&i.Output,
		&i.Status,
		&i.LatencyMs,
		&i.Error,
		&i.CreatedAt,
		&i.ToolVersionID,
	)
	return i, err
}

const getToolLastSuccessfulTestRunForVersion = `-- name: GetToolLastSuccessfulTestRunForVersion :one
SELECT id, tool_id, input, output, status, latency_ms, error, created_at, tool_version_id FROM tool_test_runs WHERE tool_version_id = $1 AND status = 'success' ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetToolLastSuccessfulTestRunForVersion(ctx context.Context, toolVersionID uuid.UUID) (ToolTestRun, error) {
	row := q.db.QueryRow(ctx, getToolLastSuccessfulTestRunForVersion, toolVersionID)
	var i ToolTestRun
	err := row.Scan(
		&i.ID,
		&i.ToolID,
		&i.Input,
		&i.Output,
		&i.Status,
		&i.LatencyMs,
		&i.Error,
		&i.CreatedAt,
		&i.ToolVersionID,
	)
	return i, err
}

const getToolLatestPublishedVersion = `-- name: GetToolLatestPublishedVersion :one
SELECT id, tool_id, version, schema_json, endpoint_config, auth_config, retry_policy, status, created_by, created_at, auth_config_encrypted FROM tool_versions WHERE tool_id = $1 AND status = 'published' ORDER BY version DESC LIMIT 1
`

func (q *Queries) GetToolLatestPublishedVersion(ctx context.Context, toolID uuid.UUID) (ToolVersion, error) {
	row := q.db.QueryRow(ctx, getToolLatestPublishedVersion, toolID)
	var i ToolVersion
	err := row.Scan(
		&i.ID,
		&i.ToolID,
		&i.Version,
		&i.SchemaJson,
		&i.EndpointConfig,
		&i.AuthConfig,
		&i.RetryPolicy,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.AuthConfigEncrypted,
	)
	return i, err
}

const getToolVersion = `-- name: GetToolVersion :one
SELECT id, tool_id, version, schema_json, endpoint_config, auth_config, retry_policy, status, created_by, created_at, auth_config_encrypted FROM tool_versions WHERE id = $1 LIMIT 1
`

func (q *Queries) GetToolVersion(ctx context.Context, id uuid.UUID) (ToolVersion, error) {
	row := q.db.QueryRow(ctx, getToolVersion, id)
	var i ToolVersion
	err := row.Scan(
		&i.ID,
		&i.ToolID,
		&i.Version,
		&i.SchemaJson,
		&i.EndpointConfig,
		&i.AuthConfig,
		&i.RetryPolicy,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.AuthConfigEncrypted,
	)
	return i, err
}

const listLegacyToolAuthVersions = `-- name: ListLegacyToolAuthVersions :many
SELECT id, tool_id, version, schema_json, endpoint_config, auth_config, retry_policy, status, created_by, created_at, auth_config_encrypted FROM tool_versions
WHERE auth_config_encrypted IS NULL
  AND btrim(auth_config) NOT IN ('', '{}')
`

func (q *Queries) ListLegacyToolAuthVersions(ctx context.Context) ([]ToolVersion, error) {
	rows, err := q.db.Query(ctx, listLegacyToolAuthVersions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ToolVersion{}
	for rows.Next() {
		var i ToolVersion
		if err := rows.Scan(
			&i.ID,
			&i.ToolID,
			&i.Version,
			&i.SchemaJson,
			&i.EndpointConfig,
			&i.AuthConfig,
			&i.RetryPolicy,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.AuthConfigEncrypted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listToolVersions = `-- name: ListToolVersions :many
SELECT id, tool_id, version, schema_json, endpoint_config, auth_config, retry_policy, status, created_by, created_at, auth_config_encrypted FROM tool_versions WHERE tool_id = $1 ORDER BY version DESC
`

func (q *Queries) ListToolVersions(ctx context.Context, toolID uuid.UUID) ([]ToolVersion, error) {
	rows, err := q.db.Query(ctx, listToolVersions, toolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ToolVersion{}
	for rows.Next() {
		var i ToolVersion
		if err := rows.Scan(
			&i.ID,
			&i.ToolID,
			&i.Version,
			&i.SchemaJson,
			&i.EndpointConfig,
			&i.AuthConfig,
			&i.RetryPolicy,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.AuthConfigEncrypted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTools = `-- name: ListTools :many
SELECT id, workspace_id, name, description, source_type, sensitive, classification_max, created_by, created_at, updated_at FROM tools WHERE workspace_id = $1 ORDER BY created_at
`

func (q *Queries) ListTools(ctx context.Context, workspaceID string) ([]Tool, error) {
	rows, err := q.db.Query(ctx, listTools, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tool{}
	for rows.Next() {
		var i Tool
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Description,
			&i.SourceType,
			&i.Sensitive,
			&i.ClassificationMax,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateToolVersionStatus = `-- name: UpdateToolVersionStatus :exec
UPDATE tool_versions SET status = $2 WHERE id = $1
`

type UpdateToolVersionStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdateToolVersionStatus(ctx context.Context, arg UpdateToolVersionStatusParams) error {
	_, err := q.db.Exec(ctx, updateToolVersionStatus, arg.ID, arg.Status)
	return err
}
